import type { ItemCategory } from '@/lib/types/database'

export interface CuratedItem {
  id: string
  title: string
  description: string
  imageUrl: string
  price: number
  retailer: string
  sourceUrl: string
  affiliateUrl?: string
  badge?: 'Popular' | 'Essential' | 'Staff Pick' | 'Great Value'
}

// ---------------------------------------------------------------------------
// Curated product catalog – real products from major retailers.
//
// Affiliate URLs: Replace the `tag` / tracking params with your own once you
// have affiliate accounts set up (Amazon Associates, Target Partners, etc.).
// For now, sourceUrl is the canonical link and affiliateUrl is a placeholder
// showing the pattern each program uses.
// ---------------------------------------------------------------------------

export const CURATED_ITEMS: Partial<Record<ItemCategory, CuratedItem[]>> = {
  // ── The Basics ──────────────────────────────────────────────────────────
  the_basics: [
    {
      id: 'basics-towel-set',
      title: 'Amazon Basics 6-Piece Bath Towel Set',
      description: 'Soft, absorbent cotton towels. The very first thing you need when you start over.',
      imageUrl: 'https://m.media-amazon.com/images/I/81tTFSBfLKL._AC_SL1500_.jpg',
      price: 26.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07QH4QLNT',
      affiliateUrl: 'https://www.amazon.com/dp/B07QH4QLNT?tag=welp-20',
      badge: 'Essential',
    },
    {
      id: 'basics-sheet-set',
      title: 'Mellanni Queen Sheet Set — 4 Piece',
      description: 'Brushed microfiber sheets. 1800 thread count. Way better than what you left behind.',
      imageUrl: 'https://m.media-amazon.com/images/I/71UDrubSqWL._AC_SL1500_.jpg',
      price: 34.97,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00NQDGYXM',
      affiliateUrl: 'https://www.amazon.com/dp/B00NQDGYXM?tag=welp-20',
      badge: 'Popular',
    },
    {
      id: 'basics-trash-cans',
      title: 'Rubbermaid 13-Gallon Step-On Trash Can',
      description: 'A grown-up trash can for your grown-up fresh start.',
      imageUrl: 'https://m.media-amazon.com/images/I/71sFmT4EmhL._AC_SL1500_.jpg',
      price: 34.98,
      retailer: 'Walmart',
      sourceUrl: 'https://www.walmart.com/ip/Rubbermaid-Step-On-Trash-Can-13-Gallon-Black/42211176',
      badge: 'Essential',
    },
    {
      id: 'basics-cleaning-kit',
      title: 'O-Cedar Easywring Microfiber Spin Mop & Bucket',
      description: 'Clean slate? Start with a clean floor.',
      imageUrl: 'https://m.media-amazon.com/images/I/71mJcSPjfyL._AC_SL1500_.jpg',
      price: 37.98,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00WSWGVZQ',
      affiliateUrl: 'https://www.amazon.com/dp/B00WSWGVZQ?tag=welp-20',
    },
    {
      id: 'basics-hangers',
      title: 'Velvet Hangers 50-Pack — Non-Slip',
      description: 'For the closet that\'s finally all yours.',
      imageUrl: 'https://m.media-amazon.com/images/I/71fdnrx5lUL._AC_SL1500_.jpg',
      price: 24.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0B2BS2CJR',
      affiliateUrl: 'https://www.amazon.com/dp/B0B2BS2CJR?tag=welp-20',
      badge: 'Great Value',
    },
  ],

  // ── Kitchen Reset ───────────────────────────────────────────────────────
  kitchen_reset: [
    {
      id: 'kitchen-pot-set',
      title: 'T-fal Initiatives Nonstick Cookware Set — 18 Piece',
      description: 'He kept the pots. These are better anyway.',
      imageUrl: 'https://m.media-amazon.com/images/I/81Whf8gJd2L._AC_SL1500_.jpg',
      price: 79.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00LBK7OSO',
      affiliateUrl: 'https://www.amazon.com/dp/B00LBK7OSO?tag=welp-20',
      badge: 'Popular',
    },
    {
      id: 'kitchen-knife-set',
      title: 'Henckels Statement 15-Piece Knife Block Set',
      description: 'Sharp knives for a sharp new you. (For cooking, obviously.)',
      imageUrl: 'https://m.media-amazon.com/images/I/71JnxqIMVpL._AC_SL1500_.jpg',
      price: 99.95,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00375MQUQ',
      affiliateUrl: 'https://www.amazon.com/dp/B00375MQUQ?tag=welp-20',
    },
    {
      id: 'kitchen-dinnerware',
      title: 'Corelle 12-Piece Dinnerware Set — Winter Frost White',
      description: 'Simple, clean plates for a simple, clean start. Service for 4 (because your friends are coming over).',
      imageUrl: 'https://m.media-amazon.com/images/I/61K7WXjCNPL._AC_SL1500_.jpg',
      price: 49.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0000CF7BO',
      affiliateUrl: 'https://www.amazon.com/dp/B0000CF7BO?tag=welp-20',
      badge: 'Essential',
    },
    {
      id: 'kitchen-coffee-maker',
      title: 'Keurig K-Mini Single Serve Coffee Maker',
      description: 'Because mornings are hard enough right now. One-cup. Just for you.',
      imageUrl: 'https://m.media-amazon.com/images/I/71MJBi7x05L._AC_SL1500_.jpg',
      price: 59.99,
      retailer: 'Target',
      sourceUrl: 'https://www.target.com/p/keurig-k-mini-single-serve-k-cup-pod-coffee-maker/-/A-53788544',
      badge: 'Staff Pick',
    },
    {
      id: 'kitchen-utensil-set',
      title: 'OXO Good Grips 15-Piece Kitchen Utensil Set',
      description: 'Spatulas, tongs, ladles — all the things you didn\'t realize you\'d need to replace.',
      imageUrl: 'https://m.media-amazon.com/images/I/81G9K7E2NeL._AC_SL1500_.jpg',
      price: 69.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07WSHSW9F',
      affiliateUrl: 'https://www.amazon.com/dp/B07WSHSW9F?tag=welp-20',
    },
  ],

  // ── Bedroom Glow-Up ─────────────────────────────────────────────────────
  bedroom_glowup: [
    {
      id: 'bedroom-comforter',
      title: 'Bedsure Queen Comforter Set — 8 Pieces',
      description: 'New bed, new sheets, new energy. The whole package.',
      imageUrl: 'https://m.media-amazon.com/images/I/71Sz3VrLLuL._AC_SL1500_.jpg',
      price: 49.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07TKNKZ4N',
      affiliateUrl: 'https://www.amazon.com/dp/B07TKNKZ4N?tag=welp-20',
      badge: 'Popular',
    },
    {
      id: 'bedroom-pillows',
      title: 'Beckham Hotel Collection Gel Pillows — Queen, 2-Pack',
      description: 'Because you deserve pillows that don\'t remind you of anyone.',
      imageUrl: 'https://m.media-amazon.com/images/I/71kL0lFj2eL._AC_SL1500_.jpg',
      price: 49.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B01LYNW421',
      affiliateUrl: 'https://www.amazon.com/dp/B01LYNW421?tag=welp-20',
      badge: 'Staff Pick',
    },
    {
      id: 'bedroom-lamp',
      title: 'Bedside Table Lamp with USB Ports & Outlets',
      description: 'Charge your phone, set the mood, sleep solo in peace.',
      imageUrl: 'https://m.media-amazon.com/images/I/61kHRfuJfzL._AC_SL1500_.jpg',
      price: 27.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B09PMGVGBP',
      affiliateUrl: 'https://www.amazon.com/dp/B09PMGVGBP?tag=welp-20',
    },
    {
      id: 'bedroom-blackout-curtains',
      title: 'NICETOWN Blackout Curtains — 2 Panels',
      description: 'Block the light. Block the memories. Sleep well.',
      imageUrl: 'https://m.media-amazon.com/images/I/71PD6sPBxsL._AC_SL1500_.jpg',
      price: 24.95,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B01586OFRK',
      affiliateUrl: 'https://www.amazon.com/dp/B01586OFRK?tag=welp-20',
      badge: 'Great Value',
    },
    {
      id: 'bedroom-full-length-mirror',
      title: 'Full Length Floor Mirror — 65" x 22"',
      description: 'Look at yourself. You\'re doing great.',
      imageUrl: 'https://m.media-amazon.com/images/I/61S2LiMQqwL._AC_SL1500_.jpg',
      price: 39.99,
      retailer: 'Walmart',
      sourceUrl: 'https://www.walmart.com/ip/Full-Length-Mirror-65-x22-Arched-Standing-Floor-Mirror/586375103',
    },
  ],

  // ── Living Solo ─────────────────────────────────────────────────────────
  living_solo: [
    {
      id: 'living-throw-blanket',
      title: 'Bedsure Fleece Throw Blanket',
      description: 'Couch, blanket, remote. The solo-living starter pack.',
      imageUrl: 'https://m.media-amazon.com/images/I/81A5GVGzm0L._AC_SL1500_.jpg',
      price: 16.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B01HPI46EC',
      affiliateUrl: 'https://www.amazon.com/dp/B01HPI46EC?tag=welp-20',
      badge: 'Great Value',
    },
    {
      id: 'living-shower-curtain',
      title: 'AmazerBath Shower Curtain Set with Hooks',
      description: 'Your bathroom. Your style. No compromises.',
      imageUrl: 'https://m.media-amazon.com/images/I/71Yz37Hse0L._AC_SL1500_.jpg',
      price: 14.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B09FHXV3FN',
      affiliateUrl: 'https://www.amazon.com/dp/B09FHXV3FN?tag=welp-20',
    },
    {
      id: 'living-bathroom-set',
      title: 'Bath Accessory Set — 4-Piece Soap Dispenser Set',
      description: 'Matching soap dispenser, toothbrush holder, tumbler. Adulting, done right.',
      imageUrl: 'https://m.media-amazon.com/images/I/71N9+FYLVbL._AC_SL1500_.jpg',
      price: 19.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0BXTLQ81Q',
      affiliateUrl: 'https://www.amazon.com/dp/B0BXTLQ81Q?tag=welp-20',
    },
    {
      id: 'living-bookshelf',
      title: 'VASAGLE 5-Tier Bookshelf — Industrial',
      description: 'Somewhere to put the books you\'ll actually read now that you have free time.',
      imageUrl: 'https://m.media-amazon.com/images/I/81cpsr+uEwL._AC_SL1500_.jpg',
      price: 45.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07SZ558K5',
      affiliateUrl: 'https://www.amazon.com/dp/B07SZ558K5?tag=welp-20',
      badge: 'Popular',
    },
    {
      id: 'living-roku-tv',
      title: 'Roku Express HD Streaming Device',
      description: 'The Netflix account was his. Time for your own everything.',
      imageUrl: 'https://m.media-amazon.com/images/I/71UFSs3-gKL._AC_SL1500_.jpg',
      price: 29.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0BCH5H2YP',
      affiliateUrl: 'https://www.amazon.com/dp/B0BCH5H2YP?tag=welp-20',
      badge: 'Essential',
    },
  ],

  // ── Self-Care & Survival ────────────────────────────────────────────────
  self_care: [
    {
      id: 'selfcare-weighted-blanket',
      title: 'YnM Weighted Blanket — 15 lbs, Queen',
      description: 'Like a hug, but it doesn\'t ask "are we okay?"',
      imageUrl: 'https://m.media-amazon.com/images/I/81+M9my-4wL._AC_SL1500_.jpg',
      price: 39.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B073429DV2',
      affiliateUrl: 'https://www.amazon.com/dp/B073429DV2?tag=welp-20',
      badge: 'Staff Pick',
    },
    {
      id: 'selfcare-essential-oils',
      title: 'Aromatherapy Essential Oil Diffuser',
      description: 'Lavender for the anxiety. Eucalyptus for the clarity. Peppermint for getting out of bed.',
      imageUrl: 'https://m.media-amazon.com/images/I/61Qs-OM1URL._AC_SL1500_.jpg',
      price: 19.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07L4R5WKT',
      affiliateUrl: 'https://www.amazon.com/dp/B07L4R5WKT?tag=welp-20',
    },
    {
      id: 'selfcare-journal',
      title: 'Papier Joy Wellness Journal',
      description: 'Write it out. Scream into pages. Process.',
      imageUrl: 'https://m.media-amazon.com/images/I/71yz2iugsTL._AC_SL1500_.jpg',
      price: 14.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B09MZFL2KN',
      affiliateUrl: 'https://www.amazon.com/dp/B09MZFL2KN?tag=welp-20',
    },
    {
      id: 'selfcare-yoga-mat',
      title: 'Gaiam Essentials Thick Yoga Mat — 72"L x 24"W',
      description: 'Stretch it out. Breathe. You\'re going to be fine.',
      imageUrl: 'https://m.media-amazon.com/images/I/81+-3HJh6ML._AC_SL1500_.jpg',
      price: 21.98,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07H9PYFRY',
      affiliateUrl: 'https://www.amazon.com/dp/B07H9PYFRY?tag=welp-20',
      badge: 'Popular',
    },
    {
      id: 'selfcare-bath-bombs',
      title: 'LifeAround2Angels Bath Bombs Gift Set — 12 Pack',
      description: 'A long bath fixes approximately 40% of life\'s problems. Science hasn\'t confirmed this yet.',
      imageUrl: 'https://m.media-amazon.com/images/I/91hRbMpyYcL._AC_SL1500_.jpg',
      price: 26.80,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B01MFBTKQI',
      affiliateUrl: 'https://www.amazon.com/dp/B01MFBTKQI?tag=welp-20',
      badge: 'Great Value',
    },
  ],

  // ── The Petty Fund ──────────────────────────────────────────────────────
  petty_fund: [
    {
      id: 'petty-ring-light',
      title: '10" Selfie Ring Light with Stand',
      description: 'For the post-breakup glow-up content.',
      imageUrl: 'https://m.media-amazon.com/images/I/71GhFk-x0FL._AC_SL1500_.jpg',
      price: 29.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B08B3X7NXC',
      affiliateUrl: 'https://www.amazon.com/dp/B08B3X7NXC?tag=welp-20',
      badge: 'Popular',
    },
    {
      id: 'petty-concert-tickets',
      title: 'Bluetooth Portable Speaker — JBL Flip 6',
      description: 'Blast your main character energy playlist. Loud.',
      imageUrl: 'https://m.media-amazon.com/images/I/71V3XoR2bGL._AC_SL1500_.jpg',
      price: 99.95,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B09GYZ7MHF',
      affiliateUrl: 'https://www.amazon.com/dp/B09GYZ7MHF?tag=welp-20',
      badge: 'Staff Pick',
    },
    {
      id: 'petty-sunglasses',
      title: 'Ray-Ban New Wayfarer Sunglasses',
      description: 'Look good. Feel good. Let them see what they\'re missing.',
      imageUrl: 'https://m.media-amazon.com/images/I/41oyUwXxQHL._AC_SL1000_.jpg',
      price: 163.00,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B001UQ71G4',
      affiliateUrl: 'https://www.amazon.com/dp/B001UQ71G4?tag=welp-20',
    },
    {
      id: 'petty-perfume',
      title: 'Versace Bright Crystal Eau de Toilette',
      description: 'Smell like revenge. The classy kind.',
      imageUrl: 'https://m.media-amazon.com/images/I/41SXDKdQK+L._SL1000_.jpg',
      price: 68.00,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B002GKKAB2',
      affiliateUrl: 'https://www.amazon.com/dp/B002GKKAB2?tag=welp-20',
    },
    {
      id: 'petty-neon-sign',
      title: 'Custom LED Neon Sign — "Living My Best Life"',
      description: 'Hang it on the wall of YOUR apartment.',
      imageUrl: 'https://m.media-amazon.com/images/I/61+baBKP7AL._AC_SL1500_.jpg',
      price: 29.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0BN4CSMC2',
      affiliateUrl: 'https://www.amazon.com/dp/B0BN4CSMC2?tag=welp-20',
      badge: 'Great Value',
    },
  ],

  // ── Treat Yo'self ───────────────────────────────────────────────────────
  treat_yoself: [
    {
      id: 'treat-air-fryer',
      title: 'Ninja Air Fryer — 4 Qt',
      description: 'Cooking for one has never been this good.',
      imageUrl: 'https://m.media-amazon.com/images/I/71MpQSh3mYL._AC_SL1500_.jpg',
      price: 69.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07FDJMC9Q',
      affiliateUrl: 'https://www.amazon.com/dp/B07FDJMC9Q?tag=welp-20',
      badge: 'Popular',
    },
    {
      id: 'treat-instant-pot',
      title: 'Instant Pot Duo 7-in-1 — 6 Qt',
      description: 'Pressure cook your feelings into a delicious meal.',
      imageUrl: 'https://m.media-amazon.com/images/I/71V1LiCjpvL._AC_SL1500_.jpg',
      price: 79.95,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00FLYWNYQ',
      affiliateUrl: 'https://www.amazon.com/dp/B00FLYWNYQ?tag=welp-20',
    },
    {
      id: 'treat-bluetooth-earbuds',
      title: 'Apple AirPods Pro (2nd Gen)',
      description: 'Noise cancelling. Block out the world. Or your ex\'s texts.',
      imageUrl: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_SL1500_.jpg',
      price: 189.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0D1XD1ZV3',
      affiliateUrl: 'https://www.amazon.com/dp/B0D1XD1ZV3?tag=welp-20',
      badge: 'Staff Pick',
    },
    {
      id: 'treat-candle-set',
      title: 'Yankee Candle Gift Set — 3 Medium Jars',
      description: 'Your place, your scents, your rules.',
      imageUrl: 'https://m.media-amazon.com/images/I/81iJr7TQAOL._AC_SL1500_.jpg',
      price: 45.00,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0BRDL7HSL',
      affiliateUrl: 'https://www.amazon.com/dp/B0BRDL7HSL?tag=welp-20',
    },
    {
      id: 'treat-robe',
      title: 'NY Threads Fleece Bathrobe',
      description: 'Sunday mornings just got a whole lot better. Treat yourself.',
      imageUrl: 'https://m.media-amazon.com/images/I/91D22EqHKnL._AC_SL1500_.jpg',
      price: 28.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B075F8RKYH',
      affiliateUrl: 'https://www.amazon.com/dp/B075F8RKYH?tag=welp-20',
      badge: 'Great Value',
    },
  ],

  // ── Fur Baby Needs ──────────────────────────────────────────────────────
  pets: [
    {
      id: 'pets-dog-bed',
      title: 'Bedsure Orthopedic Dog Bed — Large',
      description: 'At least the dog still loves you unconditionally. Give them a proper bed.',
      imageUrl: 'https://m.media-amazon.com/images/I/81Mn+pShmGL._AC_SL1500_.jpg',
      price: 39.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07MG48WXG',
      affiliateUrl: 'https://www.amazon.com/dp/B07MG48WXG?tag=welp-20',
      badge: 'Popular',
    },
    {
      id: 'pets-cat-tree',
      title: 'FEANDREA Cat Tree — 41.3" Multi-Level',
      description: 'Your cat already owned the apartment. Now make it official.',
      imageUrl: 'https://m.media-amazon.com/images/I/71KZS39Q3lL._AC_SL1500_.jpg',
      price: 45.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B083LSVV2Z',
      affiliateUrl: 'https://www.amazon.com/dp/B083LSVV2Z?tag=welp-20',
    },
    {
      id: 'pets-automatic-feeder',
      title: 'PetSafe Automatic Pet Feeder',
      description: 'For the days when getting out of bed is the real challenge.',
      imageUrl: 'https://m.media-amazon.com/images/I/71yQSRbX8YL._AC_SL1500_.jpg',
      price: 54.95,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00VIXRB6O',
      affiliateUrl: 'https://www.amazon.com/dp/B00VIXRB6O?tag=welp-20',
      badge: 'Staff Pick',
    },
    {
      id: 'pets-leash-set',
      title: 'Primal Pet Gear Dog Leash & Collar Set',
      description: 'New walks. New routes. New you (with your best friend).',
      imageUrl: 'https://m.media-amazon.com/images/I/71m4mxJL4QL._AC_SL1500_.jpg',
      price: 14.97,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B01ITESXO2',
      affiliateUrl: 'https://www.amazon.com/dp/B01ITESXO2?tag=welp-20',
      badge: 'Great Value',
    },
    {
      id: 'pets-pet-camera',
      title: 'Furbo 360° Dog Camera with Treat Tossing',
      description: 'Check in on your best friend while you\'re at work rebuilding your life.',
      imageUrl: 'https://m.media-amazon.com/images/I/61-Zf2TCIQL._AC_SL1500_.jpg',
      price: 49.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0C5LKDFMD',
      affiliateUrl: 'https://www.amazon.com/dp/B0C5LKDFMD?tag=welp-20',
    },
  ],
}

/** Get the unique retailers present in a category's curated items */
export function getRetailersForCategory(category: ItemCategory): string[] {
  const items = CURATED_ITEMS[category] ?? []
  return [...new Set(items.map((i) => i.retailer))]
}
