import type { ItemCategory } from '@/lib/types/database'

export interface CuratedItem {
  id: string
  title: string
  description: string
  imageUrl: string
  price: number
  retailer: string
  sourceUrl: string
  affiliateUrl?: string
  badge?: 'Popular' | 'Essential' | 'Staff Pick' | 'Great Value'
}

// ---------------------------------------------------------------------------
// Curated product catalog – real products from major retailers.
//
// Affiliate URLs: Replace the `tag` / tracking params with your own once you
// have affiliate accounts set up (Amazon Associates, Target Partners, etc.).
// For now, sourceUrl is the canonical link and affiliateUrl is a placeholder
// showing the pattern each program uses.
// ---------------------------------------------------------------------------

export const CURATED_ITEMS: Partial<Record<ItemCategory, CuratedItem[]>> = {
  // ── The Basics ──────────────────────────────────────────────────────────
  the_basics: [
    {
      id: 'basics-towel-set',
      title: 'Amazon Basics 6-Piece Bath Towel Set',
      description: 'Soft, absorbent cotton towels. The very first thing you need when you start over.',
      imageUrl: 'https://m.media-amazon.com/images/I/81Ryl3HyWuL._AC_SL1500_.jpg',
      price: 21.59,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00Q7JFDKK',
      affiliateUrl: 'https://www.amazon.com/dp/B00Q7JFDKK?tag=welp20-20',
      badge: 'Essential',
    },
    {
      id: 'basics-sheet-set',
      title: 'Mellanni Queen Sheet Set — 4 Piece',
      description: 'Brushed microfiber sheets. 1800 thread count. Way better than what you left behind.',
      imageUrl: 'https://m.media-amazon.com/images/I/81KFkAfIu2L._AC_SL1500_.jpg',
      price: 39.97,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07R5VP98P',
      affiliateUrl: 'https://www.amazon.com/dp/B07R5VP98P?tag=welp20-20',
      badge: 'Popular',
    },
    {
      id: 'basics-trash-cans',
      title: 'Rubbermaid 13-Gallon Step-On Trash Can',
      description: 'A grown-up trash can for your grown-up fresh start.',
      imageUrl: 'https://m.media-amazon.com/images/I/61kSAZ-+zPL._AC_SL1500_.jpg',
      price: 62.2,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B08LMY5PK9',
      badge: 'Essential',
    },
    {
      id: 'basics-cleaning-kit',
      title: 'O-Cedar Easywring Microfiber Spin Mop & Bucket',
      description: 'Clean slate? Start with a clean floor.',
      imageUrl: 'https://m.media-amazon.com/images/I/91LZ6GKDrGL._AC_SL1500_.jpg',
      price: 49.96,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B08ZBDK8BT',
      affiliateUrl: 'https://www.amazon.com/dp/B08ZBDK8BT?tag=welp20-20',
    },
    {
      id: 'basics-hangers',
      title: 'Velvet Hangers 50-Pack — Non-Slip',
      description: 'For the closet that\'s finally all yours.',
      imageUrl: 'https://m.media-amazon.com/images/I/71wx4QZRZ+L._AC_SL1500_.jpg',
      price: 20.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0FWB7LGDF',
      affiliateUrl: 'https://www.amazon.com/dp/B0FWB7LGDF?tag=welp20-20',
      badge: 'Great Value',
    },
  ],

  // ── Kitchen Reset ───────────────────────────────────────────────────────
  kitchen_reset: [
    {
      id: 'kitchen-pot-set',
      title: 'T-fal Initiatives Nonstick Cookware Set — 18 Piece',
      description: 'They kept the pots. These are better anyway.',
      imageUrl: 'https://m.media-amazon.com/images/I/713j2j371bL._AC_SL1500_.jpg',
      price: 159.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00NQ7QFGM',
      affiliateUrl: 'https://www.amazon.com/dp/B00NQ7QFGM?tag=welp20-20',
      badge: 'Popular',
    },
    {
      id: 'kitchen-knife-set',
      title: 'Henckels Statement 15-Piece Knife Block Set',
      description: 'Sharp knives for a sharp new you. (For cooking, obviously.)',
      imageUrl: 'https://m.media-amazon.com/images/I/71rre+Q8cPL._AC_SL1500_.jpg',
      price: 193.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0CMR563MJ',
      affiliateUrl: 'https://www.amazon.com/dp/B0CMR563MJ?tag=welp20-20',
    },
    {
      id: 'kitchen-dinnerware',
      title: 'Corelle 12-Piece Dinnerware Set — Winter Frost White',
      description: 'Simple, clean plates for a simple, clean start. Service for 4 (because your friends are coming over).',
      imageUrl: 'https://m.media-amazon.com/images/I/41V0n5OzOKL._AC_SL1500_.jpg',
      price: 60.8,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00R790CLY',
      affiliateUrl: 'https://www.amazon.com/dp/B00R790CLY?tag=welp20-20',
      badge: 'Essential',
    },
    {
      id: 'kitchen-coffee-maker',
      title: 'Keurig K-Mini Single Serve Coffee Maker',
      description: 'Because mornings are hard enough right now. One-cup. Just for you.',
      imageUrl: 'https://m.media-amazon.com/images/I/61UTFJux1pL._AC_SL1500_.jpg',
      price: 59.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07GV2S1GS',
      badge: 'Staff Pick',
    },
    {
      id: 'kitchen-utensil-set',
      title: 'OXO Good Grips 15-Piece Kitchen Utensil Set',
      description: 'Spatulas, tongs, ladles — all the things you didn\'t realize you\'d need to replace.',
      imageUrl: 'https://m.media-amazon.com/images/I/91SbKnsPNVL._AC_SL1500_.jpg',
      price: 124.95,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0CB74S71N',
      affiliateUrl: 'https://www.amazon.com/dp/B0CB74S71N?tag=welp20-20',
    },
  ],

  // ── Bedroom Glow-Up ─────────────────────────────────────────────────────
  bedroom_glowup: [
    {
      id: 'bedroom-comforter',
      title: 'Bedsure Queen Comforter Set — 8 Pieces',
      description: 'New bed, new sheets, new energy. The whole package.',
      imageUrl: 'https://m.media-amazon.com/images/I/81n6DEIz59L._AC_SL1500_.jpg',
      price: 46.49,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B09SHR9KVZ',
      affiliateUrl: 'https://www.amazon.com/dp/B09SHR9KVZ?tag=welp20-20',
      badge: 'Popular',
    },
    {
      id: 'bedroom-pillows',
      title: 'Beckham Hotel Collection Gel Pillows — Queen, 2-Pack',
      description: 'Because you deserve pillows that don\'t remind you of anyone.',
      imageUrl: 'https://m.media-amazon.com/images/I/71329CVoVDL._AC_SL1500_.jpg',
      price: 59.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B01LYNW421',
      affiliateUrl: 'https://www.amazon.com/dp/B01LYNW421?tag=welp20-20',
      badge: 'Staff Pick',
    },
    {
      id: 'bedroom-lamp',
      title: 'Bedside Table Lamp with USB Ports & Outlets',
      description: 'Charge your phone, set the mood, sleep solo in peace.',
      imageUrl: 'https://m.media-amazon.com/images/I/71zreHoOzVL._AC_SL1500_.jpg',
      price: 19.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0BZXNSW5K',
      affiliateUrl: 'https://www.amazon.com/dp/B0BZXNSW5K?tag=welp20-20',
    },
    {
      id: 'bedroom-blackout-curtains',
      title: 'NICETOWN Blackout Curtains — 2 Panels',
      description: 'Block the light. Block the memories. Sleep well.',
      imageUrl: 'https://m.media-amazon.com/images/I/517kFeK7FVL._AC_SL1500_.jpg',
      price: 27.19,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07CJH69NS',
      affiliateUrl: 'https://www.amazon.com/dp/B07CJH69NS?tag=welp20-20',
      badge: 'Great Value',
    },
    {
      id: 'bedroom-full-length-mirror',
      title: 'Full Length Floor Mirror — 65" x 22"',
      description: 'Look at yourself. You\'re doing great.',
      imageUrl: 'https://m.media-amazon.com/images/I/811guncJfEL._AC_SL1500_.jpg',
      price: 142.48,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0F8Q99V1Y',
    },
  ],

  // ── Living Solo ─────────────────────────────────────────────────────────
  living_solo: [
    {
      id: 'living-throw-blanket',
      title: 'Bedsure Fleece Throw Blanket',
      description: 'Couch, blanket, remote. The solo-living starter pack.',
      imageUrl: 'https://m.media-amazon.com/images/I/81IRPstYo8L._AC_SL1500_.jpg',
      price: 13.49,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0BPLB81LX',
      affiliateUrl: 'https://www.amazon.com/dp/B0BPLB81LX?tag=welp20-20',
      badge: 'Great Value',
    },
    {
      id: 'living-shower-curtain',
      title: 'AmazerBath Shower Curtain Set with Hooks',
      description: 'Your bathroom. Your style. No compromises.',
      imageUrl: 'https://m.media-amazon.com/images/I/71mlLEeEhSL._AC_SL1500_.jpg',
      price: 19.59,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0CLRVYLK1',
      affiliateUrl: 'https://www.amazon.com/dp/B0CLRVYLK1?tag=welp20-20',
    },
    {
      id: 'living-bathroom-set',
      title: 'Bath Accessory Set — 4-Piece Soap Dispenser Set',
      description: 'Matching soap dispenser, toothbrush holder, tumbler. Adulting, done right.',
      imageUrl: 'https://m.media-amazon.com/images/I/61citboYz-L._AC_SL1500_.jpg',
      price: 34.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0G93D788B',
      affiliateUrl: 'https://www.amazon.com/dp/B0G93D788B?tag=welp20-20',
    },
    {
      id: 'living-bookshelf',
      title: 'VASAGLE 5-Tier Bookshelf — Industrial',
      description: 'Somewhere to put the books you\'ll actually read now that you have free time.',
      imageUrl: 'https://m.media-amazon.com/images/I/71uGd95XkSL._AC_SL1500_.jpg',
      price: 79.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0851G6TQQ',
      affiliateUrl: 'https://www.amazon.com/dp/B0851G6TQQ?tag=welp20-20',
      badge: 'Popular',
    },
    {
      id: 'living-roku-tv',
      title: 'Roku Express HD Streaming Device',
      description: 'The Netflix account was theirs. Time for your own everything.',
      imageUrl: 'https://m.media-amazon.com/images/I/61fqMwHNQQL._AC_SL1500_.jpg',
      price: 31.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B09HR7SWTR',
      affiliateUrl: 'https://www.amazon.com/dp/B09HR7SWTR?tag=welp20-20',
      badge: 'Essential',
    },
  ],

  // ── Self-Care & Survival ────────────────────────────────────────────────
  self_care: [
    {
      id: 'selfcare-weighted-blanket',
      title: 'YnM Weighted Blanket — 15 lbs, Queen',
      description: 'Like a hug, but it doesn\'t ask "are we okay?"',
      imageUrl: 'https://m.media-amazon.com/images/I/71u5KOtpvCL._AC_SL1500_.jpg',
      price: 52.98,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B088ZT5Q84',
      affiliateUrl: 'https://www.amazon.com/dp/B088ZT5Q84?tag=welp20-20',
      badge: 'Staff Pick',
    },
    {
      id: 'selfcare-essential-oils',
      title: 'Aromatherapy Essential Oil Diffuser',
      description: 'Lavender for the anxiety. Eucalyptus for the clarity. Peppermint for getting out of bed.',
      imageUrl: 'https://m.media-amazon.com/images/I/51yopCzSgXL._AC_SL1500_.jpg',
      price: 99.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0FVSLTZXG',
      affiliateUrl: 'https://www.amazon.com/dp/B0FVSLTZXG?tag=welp20-20',
    },
    {
      id: 'selfcare-journal',
      title: 'Papier Joy Wellness Journal',
      description: 'Write it out. Scream into pages. Process.',
      imageUrl: 'https://m.media-amazon.com/images/I/516HvTRSbpL._AC_SL1500_.jpg',
      price: 27.2,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0CHF52V4W',
      affiliateUrl: 'https://www.amazon.com/dp/B0CHF52V4W?tag=welp20-20',
    },
    {
      id: 'selfcare-yoga-mat',
      title: 'Gaiam Essentials Thick Yoga Mat — 72"L x 24"W',
      description: 'Stretch it out. Breathe. You\'re going to be fine.',
      imageUrl: 'https://m.media-amazon.com/images/I/615B5V1LO3L._AC_SL1500_.jpg',
      price: 37.38,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0DN5X8TZX',
      affiliateUrl: 'https://www.amazon.com/dp/B0DN5X8TZX?tag=welp20-20',
      badge: 'Popular',
    },
    {
      id: 'selfcare-bath-bombs',
      title: 'LifeAround2Angels Bath Bombs Gift Set — 12 Pack',
      description: 'A long bath fixes approximately 40% of life\'s problems. Science hasn\'t confirmed this yet.',
      imageUrl: 'https://m.media-amazon.com/images/I/91dSs7Lcs4L._AC_SL1500_.jpg',
      price: 28.6,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B01MFGN8S5',
      affiliateUrl: 'https://www.amazon.com/dp/B01MFGN8S5?tag=welp20-20',
      badge: 'Great Value',
    },
  ],

  // ── The Petty Fund ──────────────────────────────────────────────────────
  petty_fund: [
    {
      id: 'petty-ring-light',
      title: '10" Selfie Ring Light with Stand',
      description: 'For the post-breakup glow-up content.',
      imageUrl: 'https://m.media-amazon.com/images/I/614uFdX4JqL._AC_SL1500_.jpg',
      price: 69.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0D5BP8XVR',
      affiliateUrl: 'https://www.amazon.com/dp/B0D5BP8XVR?tag=welp20-20',
      badge: 'Popular',
    },
    {
      id: 'petty-concert-tickets',
      title: 'Bluetooth Portable Speaker — JBL Flip 6',
      description: 'Blast your main character energy playlist. Loud.',
      imageUrl: 'https://m.media-amazon.com/images/I/61Eaj593GtL._AC_SL1500_.jpg',
      price: 109.95,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B09GJVTRNZ',
      affiliateUrl: 'https://www.amazon.com/dp/B09GJVTRNZ?tag=welp20-20',
      badge: 'Staff Pick',
    },
    {
      id: 'petty-sunglasses',
      title: 'Ray-Ban New Wayfarer Sunglasses',
      description: 'Look good. Feel good. Let them see what they\'re missing.',
      imageUrl: 'https://m.media-amazon.com/images/I/4108kG4wBHL._AC_SL1500_.jpg',
      price: 178,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B09G3LZYDH',
      affiliateUrl: 'https://www.amazon.com/dp/B09G3LZYDH?tag=welp20-20',
    },
    {
      id: 'petty-perfume',
      title: 'Versace Bright Crystal Eau de Toilette',
      description: 'Smell like revenge. The classy kind.',
      imageUrl: 'https://m.media-amazon.com/images/I/6125lVrrIgL._AC_SL1500_.jpg',
      price: 92.09,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00KXBUN62',
      affiliateUrl: 'https://www.amazon.com/dp/B00KXBUN62?tag=welp20-20',
    },
    {
      id: 'petty-neon-sign',
      title: 'DECANIT "Good Vibes" LED Neon Sign — Warm White',
      description: 'Hang it on the wall of YOUR apartment.',
      imageUrl: 'https://m.media-amazon.com/images/I/61LyVGbccDL._AC_SL1500_.jpg',
      price: 19.90,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B09T5S8K4F',
      affiliateUrl: 'https://www.amazon.com/dp/B09T5S8K4F?tag=welp20-20',
      badge: 'Great Value',
    },
  ],

  // ── Treat Yo'self ───────────────────────────────────────────────────────
  treat_yoself: [
    {
      id: 'treat-air-fryer',
      title: 'Ninja Air Fryer — 4 Qt',
      description: 'Cooking for one has never been this good.',
      imageUrl: 'https://m.media-amazon.com/images/I/71+8uTMDRFL._AC_SL1500_.jpg',
      price: 109,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07FDJMC9Q',
      affiliateUrl: 'https://www.amazon.com/dp/B07FDJMC9Q?tag=welp20-20',
      badge: 'Popular',
    },
    {
      id: 'treat-instant-pot',
      title: 'Instant Pot Duo 7-in-1 — 6 Qt',
      description: 'Pressure cook your feelings into a delicious meal.',
      imageUrl: 'https://m.media-amazon.com/images/I/71xbdrK1vOL._AC_SL1500_.jpg',
      price: 169.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B08PQ2KWHS',
      affiliateUrl: 'https://www.amazon.com/dp/B08PQ2KWHS?tag=welp20-20',
    },
    {
      id: 'treat-bluetooth-earbuds',
      title: 'Apple AirPods Pro (2nd Gen)',
      description: 'Noise cancelling. Block out the world. Or your ex\'s texts.',
      imageUrl: 'https://m.media-amazon.com/images/I/61solmQSSlL._AC_SL1500_.jpg',
      price: 224,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0FQFB8FMG',
      affiliateUrl: 'https://www.amazon.com/dp/B0FQFB8FMG?tag=welp20-20',
      badge: 'Staff Pick',
    },
    {
      id: 'treat-candle-set',
      title: 'Yankee Candle Gift Set — 3 Medium Jars',
      description: 'Your place, your scents, your rules.',
      imageUrl: 'https://m.media-amazon.com/images/I/31FxRgnVobL._AC_SL1500_.jpg',
      price: 24.95,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07NPV7VD3',
      affiliateUrl: 'https://www.amazon.com/dp/B07NPV7VD3?tag=welp20-20',
    },
    {
      id: 'treat-robe',
      title: 'NY Threads Fleece Bathrobe',
      description: 'Sunday mornings just got a whole lot better. Treat yourself.',
      imageUrl: 'https://m.media-amazon.com/images/I/81TCDEcFLAL._AC_SL1500_.jpg',
      price: 19.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07YDL169Y',
      affiliateUrl: 'https://www.amazon.com/dp/B07YDL169Y?tag=welp20-20',
      badge: 'Great Value',
    },
  ],

  // ── Fur Baby Needs ──────────────────────────────────────────────────────
  pets: [
    {
      id: 'pets-dog-bed',
      title: 'Bedsure Orthopedic Dog Bed — Large',
      description: 'At least the dog still loves you unconditionally. Give them a proper bed.',
      imageUrl: 'https://m.media-amazon.com/images/I/71ulVPMOYZL._AC_SL1500_.jpg',
      price: 45.58,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0C7C6WFR1',
      affiliateUrl: 'https://www.amazon.com/dp/B0C7C6WFR1?tag=welp20-20',
      badge: 'Popular',
    },
    {
      id: 'pets-cat-tree',
      title: 'FEANDREA Cat Tree — 41.3" Multi-Level',
      description: 'Your cat already owned the apartment. Now make it official.',
      imageUrl: 'https://m.media-amazon.com/images/I/81lTxTOX6rL._AC_SL1500_.jpg',
      price: 67.49,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B096M9XDRM',
      affiliateUrl: 'https://www.amazon.com/dp/B096M9XDRM?tag=welp20-20',
    },
    {
      id: 'pets-automatic-feeder',
      title: 'PetSafe Automatic Pet Feeder',
      description: 'For the days when getting out of bed is the real challenge.',
      imageUrl: 'https://m.media-amazon.com/images/I/61ibQm-eVDL._AC_SL1500_.jpg',
      price: 120.69,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07NR47N2Q',
      affiliateUrl: 'https://www.amazon.com/dp/B07NR47N2Q?tag=welp20-20',
      badge: 'Staff Pick',
    },
    {
      id: 'pets-leash-set',
      title: 'Primal Pet Gear Dog Leash & Collar Set',
      description: 'New walks. New routes. New you (with your best friend).',
      imageUrl: 'https://m.media-amazon.com/images/I/6141zIIPncL._AC_SL1500_.jpg',
      price: 18.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0FKGW86GH',
      affiliateUrl: 'https://www.amazon.com/dp/B0FKGW86GH?tag=welp20-20',
      badge: 'Great Value',
    },
    {
      id: 'pets-pet-camera',
      title: 'Furbo 360° Dog Camera with Treat Tossing',
      description: 'Check in on your best friend while you\'re at work rebuilding your life.',
      imageUrl: 'https://m.media-amazon.com/images/I/616wRFOTA5L._AC_SL1500_.jpg',
      price: 184,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B09GDQZLD1',
      affiliateUrl: 'https://www.amazon.com/dp/B09GDQZLD1?tag=welp20-20',
    },
  ],

  // ── For the Kids ────────────────────────────────────────────────────────
  for_the_kids: [
    {
      id: 'kids-twin-sheet-set',
      title: '1500 Supreme Kids Twin Sheet Set — Soft Microfiber',
      description: 'Soft, cozy sheets so the kids have a bed that feels like theirs. Fun prints that make a new room feel like home.',
      imageUrl: 'https://m.media-amazon.com/images/I/71HFDgTVSYL._AC_SX679_.jpg',
      price: 25.98,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B07PTZYP17',
      affiliateUrl: 'https://www.amazon.com/dp/B07PTZYP17?tag=welp20-20',
      badge: 'Essential',
    },
    {
      id: 'kids-backpack',
      title: 'Amazon Basics Classic School Backpack',
      description: 'Every kid needs their own backpack. Durable, roomy, and ready for whatever comes next.',
      imageUrl: 'https://m.media-amazon.com/images/I/71TrNZRQbdL._AC_SY879_.jpg',
      price: 29.28,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B013TGEJEE',
      affiliateUrl: 'https://www.amazon.com/dp/B013TGEJEE?tag=welp20-20',
      badge: 'Essential',
    },
    {
      id: 'kids-lunch-box',
      title: 'Bentgo Kids Bento Lunch Box — 5 Compartments',
      description: 'Five compartments. Leak-proof. Makes packing lunch feel a little less chaotic.',
      imageUrl: 'https://m.media-amazon.com/images/I/71aP1C0+oZL._AC_SX679_.jpg',
      price: 29.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00PKNO7LK',
      affiliateUrl: 'https://www.amazon.com/dp/B00PKNO7LK?tag=welp20-20',
      badge: 'Popular',
    },
    {
      id: 'kids-night-light',
      title: 'JolyWell Night Light for Kids — Rechargeable',
      description: 'Soft LED night light with touch control. Because new rooms can be scary at first.',
      imageUrl: 'https://m.media-amazon.com/images/I/51ijARMN4NL._AC_SX679_.jpg',
      price: 21.98,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B097YP171M',
      affiliateUrl: 'https://www.amazon.com/dp/B097YP171M?tag=welp20-20',
    },
    {
      id: 'kids-water-bottle',
      title: 'CamelBak Eddy+ Kids Insulated Water Bottle',
      description: 'Spill-proof, bite-valve stainless steel bottle. Built to survive backpacks and lunch tables.',
      imageUrl: 'https://m.media-amazon.com/images/I/71iULr37NjL._AC_SX679_.jpg',
      price: 22.99,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B09KTFVNK1',
      affiliateUrl: 'https://www.amazon.com/dp/B09KTFVNK1?tag=welp20-20',
      badge: 'Great Value',
    },
    {
      id: 'kids-art-supplies',
      title: 'Crayola Inspiration Art Case — 140 Pieces',
      description: 'Crayons, markers, colored pencils — everything they need to make the new place feel like theirs.',
      imageUrl: 'https://m.media-amazon.com/images/I/81uy6PM0NvL._AC_SX679_.jpg',
      price: 24.49,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B00TFWOS8Y',
      affiliateUrl: 'https://www.amazon.com/dp/B00TFWOS8Y?tag=welp20-20',
      badge: 'Staff Pick',
    },
    {
      id: 'kids-bath-towels',
      title: 'KeaBabies Organic Hooded Bath Towel for Kids',
      description: 'Soft organic cotton hooded towel. The little things that make a new bathroom feel like home.',
      imageUrl: 'https://m.media-amazon.com/images/I/81N3U8ISCvL._SX679_.jpg',
      price: 21.96,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B0CQTC3ZMM',
      affiliateUrl: 'https://www.amazon.com/dp/B0CQTC3ZMM?tag=welp20-20',
    },
    {
      id: 'kids-storage-bins',
      title: 'Humble Crew Kids Toy Storage Organizer — 12 Bins',
      description: 'A place for all their stuff. Helps them feel settled when everything has a spot.',
      imageUrl: 'https://m.media-amazon.com/images/I/71UDtqW-4XL._AC_SX679_.jpg',
      price: 52.65,
      retailer: 'Amazon',
      sourceUrl: 'https://www.amazon.com/dp/B000067PTO',
      affiliateUrl: 'https://www.amazon.com/dp/B000067PTO?tag=welp20-20',
      badge: 'Popular',
    },
  ],
}

/** Get the unique retailers present in a category's curated items */
export function getRetailersForCategory(category: ItemCategory): string[] {
  const items = CURATED_ITEMS[category] ?? []
  return [...new Set(items.map((i) => i.retailer))]
}
